<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  wcm.io
  %%
  Copyright (C) 2016 wcm.io
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.wcm.samples</groupId>
    <artifactId>io.wcm.caconfig.sample-app.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../parent/pom.xml</relativePath>
  </parent>

  <groupId>io.wcm.samples</groupId>
  <artifactId>io.wcm.caconfig.sample-app.complete.config-definition</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>config-definition</packaging>

  <properties>
    <config.environment>development</config.environment>
  </properties>

  <dependencies>

    <!-- Use generic AEM CMS and Dispatcher roles -->
    <dependency>
      <groupId>io.wcm.devops.conga.definitions</groupId>
      <artifactId>io.wcm.devops.conga.definitions.aem</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- Application packages -->
    <dependency>
      <groupId>io.wcm.samples</groupId>
      <artifactId>io.wcm.caconfig.sample-app.core</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm.samples</groupId>
      <artifactId>io.wcm.caconfig.sample-app.conf-content</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>zip</type>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm.samples</groupId>
      <artifactId>io.wcm.caconfig.sample-app.sample-content-default</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>zip</type>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm.samples</groupId>
      <artifactId>io.wcm.caconfig.sample-app.sample-content-aempage</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>zip</type>
      <scope>compile</scope>
    </dependency>

    <!-- Apache Sling -->
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.caconfig.api</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.caconfig.spi</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.caconfig.impl</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.models.caconfig</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- wcm.io -->
    <dependency>
      <groupId>io.wcm</groupId>
      <artifactId>io.wcm.caconfig.editor</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm</groupId>
      <artifactId>io.wcm.caconfig.extensions</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm</groupId>
      <artifactId>io.wcm.wcm.ui.granite</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.wcm</groupId>
      <artifactId>io.wcm.sling.commons</artifactId>
      <scope>compile</scope>
    </dependency>

  </dependencies>

  <build>

    <plugins>

      <plugin>
        <groupId>io.wcm.devops.conga</groupId>
        <artifactId>conga-maven-plugin</artifactId>
        <executions>

          <!-- Generate configuration for environments defined in this application code repository -->
          <execution>
            <id>environment-config</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>

        </executions>
      </plugin>

      <plugin>
        <groupId>io.wcm.devops.conga.plugins</groupId>
        <artifactId>conga-aem-maven-plugin</artifactId>
        <executions>

          <!-- Generate "all" packages including all packages from CONGA configuration for deployment via Adobe Cloud Manager -->
          <execution>
            <id>cloudmanager-all-package</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>cloudmanager-all-package</goal>
            </goals>
            <configuration>
              <group>wcm-io-samples</group>
              <runModeOptimization>ELIMINATE_DUPLICATES</runModeOptimization>
            </configuration>
          </execution>

          <!-- Generate Dispatcher configuration ZIP file for deployment via Adobe Cloud Manager -->
          <execution>
            <id>cloudmanager-dispatcher-config</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>cloudmanager-dispatcher-config</goal>
            </goals>
          </execution>

        </executions>
      </plugin>

      <plugin>
        <groupId>com.adobe.aem</groupId>
        <artifactId>aemanalyser-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>aem-analyser</id>
            <goals>
              <goal>project-analyse</goal>
            </goals>
            <configuration>
              <!-- Validate "all" packages generated by CONGA -->
              <contentPackageFiles>
                <file>${project.build.directory}/cloud.all.zip</file>
              </contentPackageFiles>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Do not generate eclipse project files -->
      <plugin>
        <groupId>io.wcm.devops.maven.plugins</groupId>
        <artifactId>eclipse-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <profiles>

    <!-- Skip building of Cloud Manager ZIP in "fast" profile -->
    <profile>
      <id>fast</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <properties>
        <conga.cloudManager.dispatcherConfig.skip>true</conga.cloudManager.dispatcherConfig.skip>
        <aem.analyser.skip>true</aem.analyser.skip>
      </properties>
    </profile>

  </profiles>

</project>
